# Generated by Django 5.1 on 2024-08-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_useranswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="selected_answer",
            field=models.BooleanField(null=True),
        ),
    ]
